# php-fpm-composer-memcache-xdebug:alpine
# php-fpm-symfony:alpine

FROM php:8.1-fpm-alpine

VOLUME /var/www/

RUN set -x \
	&& apk update \
	&& apk add --no-cache --virtual .phpize-deps autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c \
	&& apk add --no-cache --virtual .build-deps zlib-dev libmemcached-dev \
	&& apk add --no-cache zlib libmemcached \
	&& printf "\n" | pecl install memcached \
	&& docker-php-ext-enable memcached \
	&& apk del .phpize-deps \
	&& apk del .build-deps

	
RUN set -x \
	&& apk add --no-cache --virtual .phpize-deps autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c \
	&& pecl install xdebug \
	&& docker-php-ext-enable xdebug \
	&& apk del .phpize-deps

#COPY docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/
	
RUN set -x \
	&& apk add --no-cache libzip icu libxslt libxml2 libpng \
	&& apk add --no-cache --virtual .ext-deps libzip-dev icu-dev libxslt-dev libxml2-dev libpng-dev \
	&& docker-php-ext-install pdo pdo_mysql zip intl xsl soap gd \
	&& apk del .ext-deps

RUN docker-php-ext-enable opcache

RUN set -x \
    && apk add --no-cache git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#RUN wget https://www.phpdoc.org/phpDocumentor.phar -O /usr/local/bin/phpDocumentor.phar \
#    && chmod 755 /usr/local/bin/phpDocumentor.phar

#RUN wget https://github.com/phpstan/phpstan/releases/download/0.11.13/phpstan.phar -O /usr/local/bin/phpstan.phar \
#    && chmod 755 /usr/local/bin/phpstan.phar

#RUN composer global require infection/infection friendsofphp/php-cs-fixer

COPY composer_bin_path.sh /etc/profile.d/

ENV ENV=/etc/profile

WORKDIR /var/www
	
EXPOSE 9001
